pyas2/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import views as auth_views
from pyas2 import views

staff_required = user_passes_test(lambda u: u.is_staff)
superuser_required = user_passes_test(lambda u: u.is_superuser)

urlpatterns = [
    url(r'^login.*', auth_views.login, {'template_name': 'admin/login.html'}, name='login'),
    url(r'^logout.*', auth_views.logout, {'next_page': 'home'}, name='logout'),
    url(r'^password_change/$', auth_views.password_change, name='password_change'),
    url(r'^password_change/done/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^home.*', login_required(views.home, login_url='login'), name='home'),
    url(r'^msearch/$', login_required(views.MessageSearch.as_view(), login_url='login'), name='msearch'),
    url(r'^message/$', login_required(views.MessageList.as_view(), login_url='login'), name='messages'),
    url(r'^message/(?P<pk>.+)/$', login_required(views.MessageDetail.as_view(), login_url='login'),
        name='message_detail'),
    url(r'^payload/(?P<pk>.+)/$', login_required(views.PayloadView.as_view(), login_url='login'), name='payload_view'),
    url(r'^mdnsearch/$', login_required(views.MDNSearch.as_view(), login_url='login'), name='mdnsearch'),
    url(r'^mdn/$', login_required(views.MDNList.as_view(), login_url='login'), name='mdns'),
    url(r'^mdn/(?P<pk>.+)/$', login_required(views.MDNView.as_view(), login_url='login'), name='mdn_view'),
    url(r'^sendmessage/$', login_required(views.SendMessage.as_view(), login_url='login'), name='sendmessage'),
    url(r'^resendmessage/(?P<pk>.+)/$', login_required(views.resend_message, login_url='login'), name='resendmessage'),
    url(r'^sendasyncmdn/$', login_required(views.send_async_mdn, login_url='login'), name='sendasyncmdn'),
    url(r'^retryfailedcomms/$', login_required(views.retry_failed_comms, login_url='login'), name='retryfailedcomms'),
    url(r'^cancelretries/(?P<pk>.+)/$', login_required(views.cancel_retries, login_url='login'), name='cancelretries'),
    url(r'^certificates/(?P<pk>.+)$', login_required(views.download_cert, login_url='login'), name='download_cert'),
    # only superuser
    url(r'^sendtestmail$', superuser_required(views.send_test_mail_managers), name='sendtestmail'),
    # as2 asynchronous mdn and message receive url
    url(r'^as2receive$', views.as2receive, name="as2-receive"),
    # catch-all
    url(r'^.*', login_required(views.home, login_url='login'), name='home'),
]

handler500 = 'pyas2.views.server_error'
handler400 = 'pyas2.views.client_error'

pyas2/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage
from django.utils.translation import ugettext as _
from django.db.models.signals import post_save
from django.dispatch import receiver
from pyas2 import pyas2init
from pyas2 import as2utils
import os


# Initialize the pyas2 settings and loggers
pyas2init.initialize()
pyas2init.initserverlogging('pyas2')

# Set default entry for selects
DEFAULT_ENTRY = ('', "---------")


# Set the storage directory for certificates
def get_certificate_path(instance, filename):
    return os.path.join(pyas2init.gsettings['root_dir'], 'certificates', filename)


class PrivateCertificate(models.Model):
    certificate = models.FileField(
        max_length=500, upload_to=get_certificate_path)
    ca_cert = models.FileField(
        max_length=500, upload_to=get_certificate_path,
        verbose_name=_('Local CA Store'), null=True, blank=True)
    certificate_passphrase = models.CharField(max_length=100)

    def __str__(self):
        return os.path.basename(self.certificate.name)


class PublicCertificate(models.Model):
    certificate = models.FileField(
        max_length=500, upload_to=get_certificate_path)
    ca_cert = models.FileField(
        max_length=500, upload_to=get_certificate_path,
        verbose_name=_('Local CA Store'), null=True, blank=True)
    verify_cert = models.BooleanField(
        verbose_name=_('Verify Certificate'), default=True,
        help_text=_('Uncheck this option to disable certificate verification.'))

    def __str__(self):
        return os.path.basename(self.certificate.name)


class Organization(models.Model):
    name = models.CharField(verbose_name=_('Organization Name'), max_length=100)
    as2_name = models.CharField(verbose_name=_('AS2 Identifier'), max_length=100, primary_key=True)
    email_address = models.EmailField(null=True, blank=True)
    encryption_key = models.ForeignKey(PrivateCertificate, related_name='enc_org', null=True, blank=True)
    signature_key = models.ForeignKey(PrivateCertificate, related_name='sign_org', null=True, blank=True)
    confirmation_message = models.CharField(
        verbose_name=_('Confirmation Message'),
        max_length=300,
        null=True,
        blank=True,
        help_text=_('Use this field to send a customized message in the MDN Confirmations for this Organization')
    )

    def __str__(self):
        return self.name


class Partner(models.Model):
    CONTENT_TYPE_CHOICES = (
        ('application/EDI-X12', 'application/EDI-X12'),
        ('application/EDIFACT', 'application/EDIFACT'),
        ('application/edi-consent', 'application/edi-consent'),
        ('application/XML', 'application/XML'),
        ('text/CSV', 'text/CSV'),
    )
    ENCRYPT_ALG_CHOICES = (
        ('des_ede3_cbc', '3DES'),
        ('des_cbc', 'DES'),
        ('aes_128_cbc', 'AES-128'),
        ('aes_192_cbc', 'AES-192'),
        ('aes_256_cbc', 'AES-256'),
        ('rc2_40_cbc', 'RC2-40'),
    )
    SIGN_ALG_CHOICES = (
        ('sha1', 'SHA-1'),
    )
    MDN_TYPE_CHOICES = (
        ('SYNC', 'Synchronous'),
        ('ASYNC', 'Asynchronous'),
    )
    confirmation_message = models.CharField(
        verbose_name=_('Confirmation Message'),
        max_length=300,
        null=True,
        blank=True,
        help_text=_('Use this field to send a customized message in the MDN Confirmations for this Partner')
    )
    name = models.CharField(verbose_name=_('Partner Name'), max_length=100)
    as2_name = models.CharField(verbose_name=_('AS2 Identifier'), max_length=100, primary_key=True)
    email_address = models.EmailField(null=True, blank=True)
    http_auth = models.BooleanField(verbose_name=_('Enable Authentication'), default=False)
    http_auth_user = models.CharField(max_length=100, null=True, blank=True)
    http_auth_pass = models.CharField(max_length=100, null=True, blank=True)
    https_ca_cert = models.FileField(
        max_length=500, upload_to=get_certificate_path,
        verbose_name=_('HTTPS Local CA Store'), null=True, blank=True)
    target_url = models.URLField()
    subject = models.CharField(max_length=255, default=_('EDI Message sent using pyas2'))
    content_type = models.CharField(max_length=100, choices=CONTENT_TYPE_CHOICES, default='application/edi-consent')
    compress = models.BooleanField(verbose_name=_('Compress Message'), default=True)
    encryption = models.CharField(max_length=20, verbose_name=_('Encrypt Message'), choices=ENCRYPT_ALG_CHOICES,
                                  null=True, blank=True)
    encryption_key = models.ForeignKey(PublicCertificate, related_name='enc_partner', null=True, blank=True)
    signature = models.CharField(max_length=20, verbose_name=_('Sign Message'), choices=SIGN_ALG_CHOICES, null=True,
                                 blank=True)
    signature_key = models.ForeignKey(PublicCertificate, related_name='sign_partner', null=True, blank=True)
    mdn = models.BooleanField(verbose_name=_('Request MDN'), default=False)
    mdn_mode = models.CharField(max_length=20, choices=MDN_TYPE_CHOICES, null=True, blank=True)
    mdn_sign = models.CharField(max_length=20, verbose_name=_('Request Signed MDN'), choices=SIGN_ALG_CHOICES,
                                null=True, blank=True)
    keep_filename = models.BooleanField(
        verbose_name=_('Keep Original Filename'),
        default=False,
        help_text=_(
            'Use Original Filename to to store file on receipt, use this option'
            ' only if you are sure partner sends unique names')
    )
    cmd_send = models.TextField(
        verbose_name=_('Command on Message Send'),
        null=True,
        blank=True,
        help_text=_(
            'Command executed after successful message send, replacements are $filename, $sender, '
            '$recevier, $messageid and any message header such as $Subject')
    )
    cmd_receive = models.TextField(
        verbose_name=_('Command on Message Receipt'),
        null=True,
        blank=True,
        help_text=_(
            'Command executed after successful message receipt, replacements are $filename, $fullfilename, '
            '$sender, $recevier, $messageid and any message header such as $Subject')
    )

    def __str__(self):
        return self.name


class Message(models.Model):
    DIRECTION_CHOICES = (
        ('IN', _('Inbound')),
        ('OUT', _('Outbound')),
    )
    STATUS_CHOICES = (
        ('S', _('Success')),
        ('E', _('Error')),
        ('W', _('Warning')),
        ('P', _('Pending')),
        ('R', _('Retry')),
        ('IP', _('In Process')),
    )
    MODE_CHOICES = (
        ('SYNC', _('Synchronous')),
        ('ASYNC', _('Asynchronous')),
    )
    # TODO: Create composite key (message_id, organization, partner)
    message_id = models.CharField(max_length=250, primary_key=True)
    headers = models.TextField(null=True)
    direction = models.CharField(max_length=5, choices=DIRECTION_CHOICES)
    timestamp = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=2, choices=STATUS_CHOICES)
    adv_status = models.TextField(null=True)
    organization = models.ForeignKey(Organization, null=True)
    partner = models.ForeignKey(Partner, null=True)
    payload = models.OneToOneField(
        'Payload', null=True, related_name='message')
    compressed = models.BooleanField(default=False)
    encrypted = models.BooleanField(default=False)
    signed = models.BooleanField(default=False)
    mdn = models.OneToOneField('MDN', null=True, related_name='omessage')
    mic = models.CharField(max_length=100, null=True)
    mdn_mode = models.CharField(max_length=5, choices=MODE_CHOICES, null=True)
    retries = models.IntegerField(null=True)

    def __str__(self):
        return self.message_id


class Payload(models.Model):
    name = models.CharField(max_length=100)
    content_type = models.CharField(max_length=255)
    file = models.TextField()

    def __str__(self):
        return self.name


class Log(models.Model):
    STATUS_CHOICES = (
        ('S', _('Success')),
        ('E', _('Error')),
        ('W', _('Warning')),
    )
    timestamp = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=2, choices=STATUS_CHOICES)
    message = models.ForeignKey(Message, related_name='logs')
    text = models.TextField()


class MDN(models.Model):
    STATUS_CHOICES = (
        ('S', _('Sent')),
        ('R', _('Received')),
        ('P', _('Pending')),
    )
    message_id = models.CharField(max_length=250, primary_key=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=2, choices=STATUS_CHOICES)
    file = models.CharField(max_length=500)
    headers = models.TextField(null=True)
    return_url = models.URLField(null=True)
    signed = models.BooleanField(default=False)

    def __str__(self):
        return self.message_id


def getorganizations():
    return [DEFAULT_ENTRY] + [(l, '%s (%s)' % (l, n)) for (l, n) in
                              Organization.objects.values_list('as2_name', 'name')]


def getpartners():
    return [DEFAULT_ENTRY] + [(l, '%s (%s)' % (l, n)) for (l, n) in Partner.objects.values_list('as2_name', 'name')]


@receiver(post_save, sender=Organization)
def check_odirs(sender, instance, created, **kwargs):
    partners = Partner.objects.all()
    for partner in partners:
        as2utils.dirshouldbethere(
            as2utils.join(pyas2init.gsettings['root_dir'], 'messages', instance.as2_name, 'inbox', partner.as2_name))
        as2utils.dirshouldbethere(
            as2utils.join(pyas2init.gsettings['root_dir'], 'messages', partner.as2_name, 'outbox', instance.as2_name))


@receiver(post_save, sender=Partner)
def check_pdirs(sender, instance, created, **kwargs):
    orgs = Organization.objects.all()
    for org in orgs:
        as2utils.dirshouldbethere(

pyas2/forms.py
from pyas2 import models
from django import forms
from pyas2 import viewlib

HIDDEN_INPUT = forms.widgets.HiddenInput


class PartnerForm(forms.ModelForm):
    def clean(self):
        cleaned_data = super(PartnerForm, self).clean()
        if cleaned_data.get('http_auth'):
            if not cleaned_data.get('http_auth_user'):
                self._errors['http_auth_user'] = self.error_class(
                    ['HTTP username is mandatory when HTTP authentication is enabled'])
            if not cleaned_data.get('http_auth_pass'):
                self._errors['http_auth_pass'] = self.error_class(
                    ['HTTP password is mandatory when HTTP authentication is enabled'])
        if cleaned_data.get('encryption') and not cleaned_data.get('encryption_key'):
            self._errors['encryption_key'] = self.error_class(
                ['Encryption Key is mandatory when message encryption is enabled'])
        if cleaned_data.get('signature') and not cleaned_data.get('signature_key'):
            self._errors['signature_key'] = self.error_class(
                ['Signature Key is mandatory when message signature is enabled'])
        if cleaned_data.get('mdn') and not cleaned_data.get('mdn_mode'):
            self._errors['mdn_mode'] = self.error_class(['MDN Mode needs to be specified'])
        if cleaned_data.get('mdn_sign') and not cleaned_data.get('signature_key'):
            self._errors['signature_key'] = self.error_class(
                ['Signature Key is mandatory when signed mdn is requested'])
        return cleaned_data

    class Meta:
        model = models.Partner
        exclude = []


class PrivateCertificateForm(forms.ModelForm):
    certificate_passphrase = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = models.PrivateCertificate
        fields = ['certificate', 'ca_cert', 'certificate_passphrase']


class Select(forms.Form):
    datefrom = forms.DateTimeField(initial=viewlib.datetimefrom)
    dateuntil = forms.DateTimeField(initial=viewlib.datetimeuntil)
    page = forms.IntegerField(required=False, initial=1, widget=HIDDEN_INPUT())
    # sortedby = forms.CharField(initial='ts',widget=HIDDENINPUT())
    # sortedasc = forms.BooleanField(initial=False,required=False,widget=HIDDENINPUT())


class MessageSearchForm(Select):
    organization = forms.ChoiceField([], required=False)
    partner = forms.ChoiceField([], required=False)
    direction = forms.ChoiceField([], required=False)
    status = forms.ChoiceField([], required=False)
    message_id = forms.CharField(required=False, label='Message ID', max_length=255)
    filename = forms.CharField(required=False, label='Payload Name', max_length=100)

    def __init__(self, *args, **kwargs):
        super(MessageSearchForm, self).__init__(*args, **kwargs)
        self.fields['organization'].choices = models.getorganizations()
        self.fields['partner'].choices = models.getpartners()
        self.fields['direction'].choices = [models.DEFAULT_ENTRY] + list(models.Message.DIRECTION_CHOICES)
        self.fields['status'].choices = [models.DEFAULT_ENTRY] + list(models.Message.STATUS_CHOICES)


class MDNSearchForm(Select):
    organization = forms.ChoiceField([], required=False)
    partner = forms.ChoiceField([], required=False)
    mdn_mode = forms.ChoiceField([], required=False)
    status = forms.ChoiceField([], required=False)
    message_id = forms.CharField(required=False, label='MDN Message ID', max_length=255)
    omessage_id = forms.CharField(required=False, label='Original Message ID', max_length=255)

    def __init__(self, *args, **kwargs):
        super(MDNSearchForm, self).__init__(*args, **kwargs)
        self.fields['organization'].choices = models.getorganizations()
        self.fields['partner'].choices = models.getpartners()
        self.fields['status'].choices = [models.DEFAULT_ENTRY] + list(models.MDN.STATUS_CHOICES)
        self.fields['mdn_mode'].choices = [models.DEFAULT_ENTRY] + list(models.Message.MODE_CHOICES)


class SendMessageForm(forms.Form):
    organization = forms.ChoiceField([], required=True)
    partner = forms.ChoiceField([], required=True)
    file = forms.FileField(required=True, allow_empty_file=False)

    def __init__(self, *args, **kwargs):
        super(SendMessageForm, self).__init__(*args, **kwargs)
        self.fields['organization'].choices = models.getorganizations()
        self.fields['partner'].choices = models.getpartners()

pyas2/templates/pyas2/mdn_list.html
{% extends "admin/base.html" %}
{% load i18n static %}
{% block title %}
MDNs
{% endblock %}

{% block content %}
    <h1>MDN List</h1>
    <table id="mdns" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>{% trans 'Timestamp' %}</th>
                <th>{% trans 'Status' %}</th>
                <th>{% trans 'Message ID' %}</th>
                <th>{% trans 'Original Message ID' %}</th>
                <th>{% trans 'Organization' %}</th>
                <th>{% trans 'Partner' %}</th>
                <th>{% trans 'Mode' %}</th>
                <th>{% trans 'Signed' %}</th>
            </tr>
        </thead>
        <tbody>
            {% for row in page_obj.object_list %}
                {% if row.omessage %}
                <tr class="{% cycle 'row1' 'row2' %}">
                    <td class="nowrap">{{row.timestamp|date:"Y-m-d H:i:s" }}</td>
                    <td class="nowrap">{{row.get_status_display}}</td>
                    <td class="nowrap"><a href="{% url "mdn_view" row.message_id %}?action=this" target="_blank" class="pyas2link">{{row.message_id}}</a></td>
                    <td class="nowrap"><a href="{% url "message_detail" row.omessage.message_id %}" target="_blank" class="pyas2link">{{row.omessage.message_id}}</a></td>
                    <td class="nowrap">{{row.omessage.organization}}</td>
                    <td class="nowrap">{{row.omessage.partner}}</td>
                    <td class="nowrap">{{row.omessage.get_mdn_mode_display}}</td>
                    <td class="nowrap">
                        {% if row.signed %}
                            <img src="{% static "admin/img/icon_success.gif" %}" style="width: 1em;"/>
                        {% else %}
                            <img src="{% static "admin/img/icon_error.gif" %}" style="width: 1em;"/>
                        {% endif %}
                    </td>
                </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>

    {% include "pyas2/pagination.html" %}
{% endblock %}

    

pyas2/templates/pyas2/mdn_search.html
{% extends "admin/base.html" %}
{% load i18n %}
{% load pyas2_extras %}
{% block title %}
Search MDNs
{% endblock %}
{% load static %}

<!-- 20/01/2012 MJG - add datetimepicker widget to the from/until dates
     http://trentrichardson.com/examples/timepicker/  -->
{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static "css/jquery-ui.min.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/jquery-ui-timepicker-addon.css" %}" />
<script src="{% static "admin/js/jquery.min.js" %}"></script>
<script src="{% static "js/jquery-ui.min.js" %}"></script>
<script src="{% static "js/jquery-ui-timepicker-addon.js" %}"></script>
<script type="text/javascript">
    $(function() {
        $("#id_datefrom").datetimepicker({
            dateFormat: 'yy-mm-dd',
            timeFormat: 'hh:mm:ss',
            minDate: {% get_init "minDate" %},
            maxDate: 0.1,
        });
        $("#id_dateuntil").datetimepicker({
            ampm: false,
            dateFormat: 'yy-mm-dd',
            timeFormat: 'hh:mm:ss',
            minDate: {% get_init "minDate" %},
            maxDate: 0.1,
        });
    });
</script>
{% endblock %}

{% block content %}
    <h1>Select MDNs</h1>
<p>&nbsp;Make your required selections below:</p>
<br/>
<form action="{{ form.action }}" method="post">{% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <br/>&nbsp;
    <p></p>
    <input type="submit" name="fromselect" value="{% trans 'Show selection' %}" />
</form>
{% endblock %}

pyas2/templates/pyas2/menu.html
{% load i18n %}
<div id="menu">
{% if user.is_authenticated %}
        <ul>
                <a {% if not pyas2_touchscreen %} href="{% url "home" %}" {% endif %} >{% trans 'Home' %}</a>
                <li><a href="{% url "home" %}">{% trans 'Home' %}{% if not pyas2_touchscreen %} *{% endif %}</a></li>
                <li><a href="{% url "logout" %}">{% trans 'Log out' %}</a></li>
                <li><a href="{% url "password_change" %}">{% trans 'Change password' %}</a></li>
        </ul>
        <ul>
                <a>{% trans 'Messages' %}</a>
                <li><a href="{% url "messages" %}" >{% trans 'All Messages' %}{% if not pyas2_touchscreen %} *{% endif %}</a></li>
                <li><a href="{% url "messages" %}?direction=IN" >{% trans 'Inbound Messages' %}</a></li>
                <li><a href="{% url "messages" %}?direction=OUT" >{% trans 'Outbound Messages' %}</a></li>
                <li><a href="{% url "msearch" %}" >{% trans 'Search Messages' %}</a></li>
                <li><a href="{% url "mdnsearch" %}" >{% trans 'Search MDNs' %}</a></li>
        </ul>
        {% if user.is_staff %}
        <ul>
                <a>{% trans 'Configuration' %}</a>
                {% if perms.pyas2.change_organization %}<li><a href="/admin/pyas2/organization/" >{% trans 'Organizations' %}</a></li>{% endif %}
                {% if perms.pyas2.change_partner %}<li><a href="/admin/pyas2/partner/" >{% trans 'Partners' %}</a></li>{% endif %}
                {% if perms.pyas2.change_privatecertificate %}<li><a href="/admin/pyas2/privatecertificate/" >{% trans 'Private Certificates' %}</a></li>{% endif %}
                {% if perms.pyas2.change_publiccertificate %}<li><a href="/admin/pyas2/publiccertificate/" >{% trans 'Public Certificates' %}</a></li>{% endif %}
        </ul>
    {% endif %}
    {% if user.is_superuser %}
        <ul>
                <a>{% trans 'Administration' %}</a>
                <li><a href="/admin/auth/user/" >{% trans 'Users' %}</a></li>
                <li><a href="/admin/auth/group/" >{% trans 'UserGroups' %}</a></li>
        <li><hr/></li>
                <li><a href="{% url "sendtestmail" %}">{% trans 'Send test report' %}</a></li>
        </ul>
    {% endif %}
        {% if perms.pyas2.change_mutex %} <!-- change mutex permission is required to run pyas2-engine! -->
        <ul>
                <a>{% trans 'Run' %}</a>
                <li><a href="{% url "sendmessage" %}" >{% trans 'Send Message' %}</a></li>
                <li><a href="{% url "sendasyncmdn" %}" >{% trans 'Send Asynchronous MDNs' %}</a></li>
                <li><a href="{% url "retryfailedcomms" %}" >{% trans 'Retry failed communications' %}</a></li>
        </ul>
        {% endif %}
        {% if custom_menus %}
        <ul>
                <a>{{ custom_menuname }}</a>
                {% for key,value in custom_menus %}
                        {% ifequal '---' value %}
                                <li><hr/></li>
                        {% else %}
                                <li><a href="{{ value }}" >{{ key }}</a></li>
                        {% endifequal %}
                {% endfor %}
    </ul>
        {% endif %}

{% else %}
        <ul>
                <a href="{% url "login" %}">{% trans 'Log in' %}</a>
        </ul>
{% endif %}
                <noscript>{% trans '*****Javascript is not enabled. Bots works better with javascript*****' %}</noscript>
</div>

pyas2/templates/pyas2/message_detail.html
{% extends "admin/base.html" %}
{% load i18n static %}
{% block title %}
Message
{% endblock %}
{% block content %}
    <h1>Details of message {{message.message_id}}</h1>
    <table>
        <tr><td>{% trans 'Timestamp' %}</td><td class="nowrap">{{message.timestamp|date:"Y-m-d H:i:s"}}</td></tr>
        <tr><td>{% trans 'Status' %}</td><td>{{message.get_status_display}}</td></tr>
        <tr><td>{% trans 'Direction' %}</td><td>{{message.get_direction_display}}</td></tr>
        <tr><td>{% trans 'Organization' %}</td><td>{{message.organization}}</td></tr>
        <tr><td>{% trans 'Partner' %}</td><td>{{message.partner}}</td></tr>
        <tr>
            <td>{% trans 'Compressed' %}</td>
            <td>
                {% if message.compressed %}
                    <img src="{% static "admin/img/icon_success.gif" %}" style="width: 1em;"/>
                {% else %}
                    <img src="{% static "admin/img/icon_error.gif" %}" style="width: 1em;"/>
                {% endif %}
            </td>
        </tr>
        <tr>
            <td>{% trans 'Encrypted' %}</td>
            <td>
                {% if message.encrypted %}
                    <img src="{% static "admin/img/icon_success.gif" %}" style="width: 1em;"/>
                {% else %}
                    <img src="{% static "admin/img/icon_error.gif" %}" style="width: 1em;"/>
                {% endif %}
            </td>
        </tr>
        <tr>
            <td>{% trans 'Signed' %}</td>
            <td>
                {% if message.signed %}
                    <img src="{% static "admin/img/icon_success.gif" %}" style="width: 1em;"/>
                {% else %}
                    <img src="{% static "admin/img/icon_error.gif" %}" style="width: 1em;"/>
                {% endif %}
            </td>
        </tr>
	    <tr>
            <td>{% trans 'Payload' %}</td>
            <td class="nowrap">{% if message.payload %} <a target="_blank" href="{% url 'payload_view' message.message_id %}?action=this">{{message.payload}}</a>{% endif %}</td>
        </tr>
        <tr><td>{% trans 'MDN' %}</td><td class="nowrap">{% if message.mdn %}<a target="_blank" href="{% url 'mdn_view' message.mdn.message_id %}?action=this">{{message.mdn}}{% endif %}</td></tr>
    </table>
    <table id="pyas2table">
        <thead>
            <tr>
                <th><button class="pyas2header" >{% trans 'Timestamp' %}</button></th>
                <th><button class="pyas2header" >{% trans 'Status' %}</button></th>
                <th><button class="pyas2header" >{% trans 'Text' %}</button></th>
        </thead>
        <tbody>
        {% for log in logs %}
            <tr class="{% cycle 'row1' 'row2' %}">
                <td class="nowrap">{{log.timestamp|date:"Y-m-d H:i:s"}}</td>
                <td>
                    {% if log.status == "S" %}
                        <img src="{% static "admin/img/icon_success.gif" %}" style="width: 1em;"/>
                    {% elif log.status == "E" %}
                        <img src="{% static "admin/img/icon_error.gif" %}" style="width: 1em;"/>
                    {% elif log.status == "W" %}
                        <img src="{% static "admin/img/icon_alert.gif" %}" style="width: 1em;"/>
                    {% endif %}
                </td>
                <td>{{log.text}}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

pyas2/templates/pyas2/pagination.html
{% load i18n pyas2_extras %}
    <div class="paginator">
        <p class="float-left">Showing {{ page_obj.start_index }} to
            {{ page_obj.end_index }} of {{ page_obj.paginator.count }} entries</p>
        <span class="step-links float-right">
            {% if page_obj.has_previous %}
                <a href="{% append_to_get page=page_obj.previous_page_number%}">Previous </a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>

            {% if page_obj.has_next %}
                <a href="{% append_to_get page=page_obj.next_page_number %}"> Next</a>
            {% endif %}
        </span>
    </div>